name: "Build BizyAir"

on:
  workflow_dispatch:
    inputs:
      cu:
        description: 'cuda version'
        required: true
        type: string
        default: "121"

      python_minor:
        description: 'python minor version'
        required: true
        type: string
        default: "11"

      python_patch:
        description: 'python patch version'
        required: true
        type: string
        default: "8"

      cpu:
        description: 'if it is a cpu build'
        required: false
        type: boolean
        default: true

      xformers:
        description: 'xformers version'
        required: false
        type: string
        default: ""

jobs:
  deps:
    uses: ./.github/workflows/windows_release_dependencies.yml
    with:
      xformers: ${{ inputs.xformers }}
      cu: ${{ inputs.cu }}
      python_minor: ${{ inputs.python_minor }}
      python_patch: ${{ inputs.python_patch }}
      cpu: ${{ inputs.cpu }}
  build:
    uses: ./.github/workflows/windows_release_package.yml
    with:
      cu: ${{ inputs.cu }}
      python_minor: ${{ inputs.python_minor }}
      python_patch: ${{ inputs.python_patch }}
      cpu: ${{ inputs.cpu }}
